"""graphify-mesh — a scheduled sync engine + companion MCP server that merges
many per-repo `graphify` knowledge graphs into one safe, repo-attributed,
human-named global graph with a cross-project dependency/similarity/API overlay.

See the `sync` subpackage for the merge/naming/embed/overlay/publish pipeline
and the `server` subpackage for the stdio MCP query server.
"""

from __future__ import annotations

try:
    # Generated by hatch-vcs at build time from the git tag (see
    # [tool.hatch.build.hooks.vcs] in pyproject.toml) — never hand-edit
    # _version.py, and never hand-edit a version string here either.
    from graphify_mesh._version import __version__
except ImportError:
    # No git tags reachable and no build has run yet (e.g. a shallow clone
    # with no tags, or source copied without git metadata) — better than a
    # crash on import, but callers should not trust this as a real version.
    __version__ = "0+unknown"
